return {
  {
    "williamboman/mason-lspconfig.nvim",
    opts = {
      ensure_installed = {
        "angularls",
        "bashls",
        "buf_ls",
        "clangd",
        "cmake",
        "cssls",
        "docker_compose_language_service",
        "dockerls",
        "gopls",
        "jdtls",
        "jsonls",
        "lua_ls",
        "marksman",
        "neocmake",
        "omnisharp",
        "ruff",
        "rust_analyzer",
        "taplo",
        "vtsls",
        "yamlls",
      },
      automatic_installation = true,
    },
  },
  {
    "williamboman/mason-nvim-dap.nvim",
    opts = {
      ensure_installed = {
        "codelldb",
        "cpptools",
        "debugpy",
        "delve",
        "java-debug-adapter",
        "java-test",
        "js-debug-adapter",
        "go-debug-adapter",
        "netcoredbg",
        "node-debug2",
      },
      automatic_installation = true,
    },
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "cmakelang",
        "cmakelint",
        "csharpier",
        "flake8",
        "hadolint",
        "markdown-toc",
        "markdownlint-cli2",
        "prettier",
        "ruff",
        "shellcheck",
        "sqlfluff",
        "stylua",
        "shfmt",
      },
      automatic_installation = true,
    },
  },
}
